# Generated by Django 4.0.1 on 2022-01-24 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('AOC', 'AOC'), ('AOP', 'AOP'), ('IGP', 'IGP'), ('VDP', 'Vin de Pays'), ('Autre', 'Autre')], default='AOC', max_length=10)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=2048, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('vintage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)])),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.classification')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.color')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.producer')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.region')),
            ],
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(fields=('name', 'domain'), name='unique_name_domain'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), ('domain__isnull', False), _connector='OR'), name='not_both_null'),
        ),
        migrations.AddField(
            model_name='classification',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='core.region'),
        ),
        migrations.AddConstraint(
            model_name='wine',
            constraint=models.UniqueConstraint(fields=('producer', 'name'), name='unique_name_producer'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.UniqueConstraint(fields=('type', 'name'), name='unique_type_name'),
        ),
    ]
