# Generated by Django 4.0.1 on 2022-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', True)), fields=('name',), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', True)), fields=('domain',), name='unique_domain'),
        ),
    ]
