# Generated by Django 4.0.1 on 2022-01-07 14:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_color_alter_classification_type_alter_region_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=2048, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(fields=('name', 'domain'), name='unique_name_domain'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), ('domain__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
