# Generated by Django 4.0.1 on 2022-01-07 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producer_address_alter_producer_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('vintage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)])),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.classification')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.color')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.producer')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='core.region')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wine',
            constraint=models.UniqueConstraint(fields=('producer', 'name'), name='unique_name_producer'),
        ),
    ]
